### PR TITLE
Fix kmeans for user defined metrics

### PR DESCRIPTION
**Pull request by Mxbonn**
User defined metrics don't always support arrays of points.

### CODE REVIEW

**Comment by annoviko** [comment]
Hi @Mxbonn,

Thank you for the correction.

**Comment by annoviko** [comment]
I want to write test before merge that will fail in order to test this problem. Could you please provide information how do you reproduce the problem?

**Comment by Mxbonn** [comment]
I created a minimum working example that fails:
```python
import math
import numpy as np

from pyclustering.cluster.kmeans import kmeans
from pyclustering.utils.metric import distance_metric, type_metric

def simple_2d_euclidean_distance(point_a, point_b):
    return math.sqrt((point_a[0] - point_b[0])**2 + (point_a[1] - point_b[1])**2)

metric = distance_metric(type_metric.USER_DEFINED, func=simple_2d_euclidean_distance)

dummy_data = np.random.rand(100,2)
dummy_centers = np.random.rand(5,2)
kmeans_instance = kmeans(dummy_data, dummy_centers, metric=metric)

kmeans_instance.process()
clusters = kmeans_instance.get_clusters()
final_centers = kmeans_instance.get_centers()
```

**Comment by annoviko** [comment]
@Mxbonn , thanks! The pull requested was merged.

**Pull request merged**
