### PR TITLE
kmedoids does *not* implement the PAM algorithm

### PR DESCRIPTION
**Pull request by kno10**
c.f. the PAM publication. The other reference is also wrong, it does nowhere seem to mention medoids at all.

This is a different algorithm, and has repeatedly been observed to produce worse results.

### CODE REVIEW

**Comment by annoviko** [comment]
Hello, @kno10,

Thank you for clarification, looks like I need to find paper that was used to implemented this particular algorithm. I will remove information about PAM to avoid confusing in documentation.

**Comment by kno10** [comment]
This approach has been discussed several times in literature:

* At least the current editions of the ESL book discuss this approach to k-medoids, but don't give references for this; rather they seem to treat this as obvious variation of k-means. T. Hastie, R. Tibshirani, and J. Friedman. The Elements of Statistical Learning, Springer (2001), 468–469.
* Reynolds already mentioned that this is possible, but produces worse results. Reynolds, A. P., Richards, G., de la Iglesia, B., & Rayward-Smith, V. J. (2006). Clustering rules: a comparison of partitioning and hierarchical clustering algorithms. Journal of Mathematical Modelling and Algorithms, 5(4), 475-504.
* Park and Jun reinvented this, without knowing that it has been discussed several times before, and without paying attention to result quality enough: H.S. Park , C.H. Jun, A simple and fast algorithm for K-medoids clustering, Expert Systems with Applications, 36, (2) (2009), 3336–3341.
(it turns out that the k-means-style approach can be pretty fast to converge - but because it stops improving when other approaches still find better local solutions that are reachable with swaps, but not with k-means-style steps)

But I have just recently come across this in a minimally different context:
* Maranzana, F. E. "On the location of supply points to minimize transport costs." Journal of the Operational Research Society 15.3 (1964): 261-270.
  appears to have already have used exactly this k-means-style algorithm
* Teitz, Michael B., and Polly Bart. "Heuristic methods for estimating the generalized vertex median of a weighted graph." Operations research 16.5 (1968): 955-961.
  already mention that swap-based methods (such as PAM) produce better results, and that the k-means-style approach "at first sight it appears attractive, but its performance may be quite erratic".
* it seems you can find several studies from the 70s and 80s that found this approach to produce much worse solutions. I did not yet have time to study all of this literature. An approach that supposedly (because it seems to consider chain swaps, haven't read this yet) can find even better solutions is this: Mladenovic, Nenad, José A. Moreno, and J. Marcos Moreno-Vega. "Chain-interchange heuristic method." Yugosl J Oper Res 6.1 (1996): 41-54.

**Comment by annoviko** [comment]
@kno10, thank you for detailed response - it is really helpful. I will look through these papers and update documentation. Also I will add task to implement PAM algorithm to backlog of the library.

**Comment by annoviko** [comment]
@kno10, mention of the PAM algorithm is removed from sources and documentations.

**Pull request closed without merging**
